#!/usr/bin/env node
/**
 * Generates `public/sw.js` before every build.
 *
 * Why this exists (§ 10.1): the browser's own service-worker update check
 * re-fetches `sw.js` on every navigation and does a byte-for-byte
 * comparison against the currently installed worker to decide whether a
 * new version exists. A hand-written, unchanging `sw.js` would therefore
 * *never* look updated to the browser, even after a real deploy — nothing
 * in its bytes would differ. Stamping a `BUILD_ID` that changes on every
 * build is what makes that comparison actually detect a new deploy, which
 * is what lets `components/site/pwa-manager.tsx` show the "update
 * available" prompt required by § 10.1's exit criteria.
 *
 * § 10.2 reuses this exact `BUILD_ID` to version the two caches below
 * ("cache versioned to the deploy; a new publish invalidates the old
 * cache") rather than inventing a second stamping mechanism.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const buildId =
  process.env.VERCEL_GIT_COMMIT_SHA || process.env.SOURCE_VERSION || String(Date.now())

const source = `// AUTO-GENERATED by scripts/generate-sw.mjs at build time. Do not edit by hand.
//
// § 10.1 lifecycle (install / activate / skip-waiting) + § 10.2 caching
// strategy (cache-first for static assets, stale-while-revalidate for
// content pages). See ROAD-MAP-ARTAVEO.md §§ 10.1-10.2 and
// docs/phases/PHASE-10.1-README.md / PHASE-10.2-README.md.
const BUILD_ID = '${buildId}';
const STATIC_CACHE = 'artaveo-static-' + BUILD_ID;
const CONTENT_CACHE = 'artaveo-content-' + BUILD_ID;
const CURRENT_CACHES = [STATIC_CACHE, CONTENT_CACHE];

// Kept in sync by hand with i18n/routing.ts's locales list — this file is
// plain JS with no build step of its own, so it can't import that config
// directly. If a locale is ever added there, add it here too.
const LOCALES = ['en', 'fa'];

// § 10.2's own list, verbatim: "Home, Work (index + case studies),
// Services (catalogue + detail), About, Process, Insights". '' stands for
// Home (i.e. the path is just /en or /fa with nothing after the locale).
// Insights ships in Phase 17 — it was listed here ahead of time, so the
// service worker needed no change beyond the extension guard below.
// Everything NOT in this list — /start, /contact, /design-system, and any
// future /admin, lead-pipeline, CMS or client-portal route — deliberately
// never matches this predicate, so the fetch handler below never
// intercepts or caches it. That's the enforcement mechanism behind
// § 10.2's "excluded from the service worker's scope entirely"
// requirement.
const CONTENT_SEGMENTS = ['', 'work', 'services', 'about', 'process', 'insights'];

function isContentPagePath(pathname) {
  // A path with a file extension (e.g. /en/insights/feed.xml, the RSS feed)
  // is a document for feed readers, not a page to keep for offline browsing.
  if (/\\.[a-z0-9]+$/i.test(pathname)) return false;
  const parts = pathname.split('/').filter(Boolean);
  if (parts.length === 0 || !LOCALES.includes(parts[0])) return false;
  if (parts.length === 1) return true; // /en or /fa — Home
  if (!CONTENT_SEGMENTS.includes(parts[1])) return false;
  return parts.length <= 3; // section index, or /section/slug — never deeper
}

// Cache-first bucket: fonts (self-hosted by next/font under
// /_next/static/media, already covered by the first prefix below), the
// logo/icon files, and every hashed CSS/JS bundle. Also covers the
// project images used on Work/case-study pages and the manifest itself —
// without these a "cached" case study page would just show broken
// images offline, which isn't meaningfully "browsable".
const STATIC_PREFIXES = ['/_next/static/', '/brand/', '/images/'];
const STATIC_EXACT_PATHS = new Set([
  '/manifest.webmanifest',
  '/favicon.ico',
  '/apple-icon.png',
  '/icon.svg',
  '/artaveo-icon.svg',
  '/Profile-pic.jpg',
]);

function isStaticAssetPath(pathname) {
  if (STATIC_EXACT_PATHS.has(pathname)) return true;
  if (pathname.startsWith('/icon-')) return true; // icon-192.png, icon-512*.png, icon-{light,dark}-*.png
  return STATIC_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && response.ok) cache.put(request, response.clone());
  return response;
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const networkPromise = fetch(request)
    .then((response) => {
      if (response && response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => undefined);
  if (cached) {
    // Refresh the cache in the background; the visitor gets the instant
    // cached response either way — that's the "stale" half of
    // stale-while-revalidate. A network failure here is not an error: it
    // just means the background refresh didn't happen this time.
    networkPromise.catch(() => {});
    return cached;
  }
  const networkResponse = await networkPromise;
  if (networkResponse) return networkResponse;
  // Nothing cached and the network failed: genuinely unavailable. Let the
  // browser show its own offline error rather than fabricating a
  // response — the same "never fake success" principle § 10.3 applies to
  // the Brief Builder applies here to page loads.
  return Response.error();
}

self.addEventListener('install', () => {
  // Intentionally does NOT call self.skipWaiting() here: a newly installed
  // worker should sit in "waiting" until the visitor chooses to reload
  // (components/site/pwa-manager.tsx), never silently take over a page
  // that's already open with in-progress state (e.g. the Brief Builder).
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith('artaveo-') && !CURRENT_CACHES.includes(key))
          .map((key) => caches.delete(key)),
      );
      await self.clients.claim();
    })(),
  );
});

// The page posts this after the visitor accepts the "update available"
// prompt, so the waiting worker activates immediately instead of waiting
// for every open tab of the old version to close on its own.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Every mutation in this app — the Brief Builder's server action today,
  // any future admin write — is a non-GET request. Never intercepting one
  // is the actual enforcement point behind "the Brief Builder's submit
  // request itself, and every other server mutation... network-only",
  // not just a path-based guess.
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // e.g. analytics, Supabase — never ours to cache

  if (isStaticAssetPath(url.pathname)) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  // Only real, top-level navigations — not Next's own RSC/client-router
  // fetches, which arrive with a different "mode" and are deliberately
  // left untouched so this worker never risks interfering with App
  // Router's own prefetch/streaming behaviour. Practical effect: a full
  // load or reload of any of § 10.2's six content-page types works
  // offline after one prior visit; a fully-offline client-side link click
  // between them is not guaranteed — see PHASE-10.2-README.md.
  if (request.mode === 'navigate' && isContentPagePath(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request, CONTENT_CACHE));
    return;
  }

  // Everything else — /start, /contact, /design-system, API routes,
  // future admin/CMS/client-portal routes, cross-origin requests, RSC
  // payload fetches — is intentionally left alone: no respondWith call
  // means the browser handles it exactly as if this worker didn't exist.
});
`

const outPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'public',
  'sw.js',
)

writeFileSync(outPath, source, 'utf8')
console.log(`[generate-sw] wrote ${outPath} (BUILD_ID=${buildId})`)
