#!/usr/bin/env node
/**
 * Generates `public/sw.js` before every build.
 *
 * Why this exists (§ 10.1): the browser's own service-worker update check
 * re-fetches `sw.js` on every navigation and does a byte-for-byte
 * comparison against the currently installed worker to decide whether a
 * new version exists. A hand-written, unchanging `sw.js` would therefore
 * *never* look updated to the browser, even after a real deploy — nothing
 * in its bytes would differ. Stamping a `BUILD_ID` that changes on every
 * build is what makes that comparison actually detect a new deploy, which
 * is what lets `components/site/pwa-manager.tsx` show the "update
 * available" prompt required by § 10.1's exit criteria.
 *
 * Scope note: this worker is lifecycle-only for § 10.1 (install / activate
 * / skip-waiting messaging) — it deliberately has no `fetch` handler and
 * caches nothing. § 10.2 adds the cache-first / stale-while-revalidate
 * strategy inside this same generated file; it will reuse this exact
 * `BUILD_ID` stamping mechanism to version its cache name rather than
 * inventing a second one.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const buildId =
  process.env.VERCEL_GIT_COMMIT_SHA || process.env.SOURCE_VERSION || String(Date.now())

const source = `// AUTO-GENERATED by scripts/generate-sw.mjs at build time. Do not edit by hand.
//
// Lifecycle-only service worker (roadmap § 10.1). No caching yet — see
// § 10.2 for the cache-first / stale-while-revalidate strategy that will
// extend this same file.
const BUILD_ID = '${buildId}';

self.addEventListener('install', () => {
  // Intentionally does NOT call self.skipWaiting() here: a newly installed
  // worker should sit in "waiting" until the visitor chooses to reload
  // (components/site/pwa-manager.tsx), never silently take over a page
  // that's already open with in-progress state (e.g. the Brief Builder).
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// The page posts this after the visitor accepts the "update available"
// prompt, so the waiting worker activates immediately instead of waiting
// for every open tab of the old version to close on its own.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
`

const outPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'public',
  'sw.js',
)

writeFileSync(outPath, source, 'utf8')
console.log(`[generate-sw] wrote ${outPath} (BUILD_ID=${buildId})`)
